version: '3'
services:
  minio:
    image: minio/minio:RELEASE.2023-07-18T17-49-40Z
    container_name: minio
    ports:
      - 9000:9000
      - 9090:9090
    env_file:
      - minio.secrets
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9090"

volumes:
  minio-data:
